package mps.samples.functions.sandbox.sandbox;

/*Generated by MPS */


public class Fibonacci {

  public Fibonacci() {
  }

  public void run() {
    double x1 = 0;
    double x2 = 1;
    double tmp_x1 = 0;
    double tmp_x2 = 1;
    int max = 10;
    for(int j = 0 ; j < max ; j++ ) {
      tmp_x1 = x2;
      tmp_x2 = x1 + x2;
      x1 = tmp_x1;
      x2 = tmp_x2;
      double F = x1;
      double R = x2 / x1;
      System.out.println("F is " + F);
      System.out.println("R is " + R);
    }
  }


  public static void main(String[] args) {
    new Fibonacci().run();
  }

}
