package mps.samples.functions.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InputReference extends Expression {
  public static final String concept = "mps.samples.functions.structure.InputReference";
  public static final String INPUT = "input";

  public InputReference(SNode node) {
    super(node);
  }

  public Input getInput() {
    return (Input)this.getReferent(Input.class, InputReference.INPUT);
  }

  public void setInput(Input node) {
    super.setReferent(InputReference.INPUT, node);
  }


  public static InputReference newInstance(SModel sm, boolean init) {
    return (InputReference)SModelUtil_new.instantiateConceptDeclaration("mps.samples.functions.structure.InputReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InputReference newInstance(SModel sm) {
    return InputReference.newInstance(sm, false);
  }

}
