package mps.samples.functions.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Output extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.samples.functions.structure.Output";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String EXPRESSION = "expression";

  public Output(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Output.NAME);
  }

  public void setName(String value) {
    this.setProperty(Output.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Output.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Output.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Output.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Output.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Output.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Output.VIRTUAL_PACKAGE, value);
  }

  public Expression getExpression() {
    return (Expression)this.getChild(Expression.class, Output.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(Output.EXPRESSION, node);
  }


  public static Output newInstance(SModel sm, boolean init) {
    return (Output)SModelUtil_new.instantiateConceptDeclaration("mps.samples.functions.structure.Output", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Output newInstance(SModel sm) {
    return Output.newInstance(sm, false);
  }

}
